---
resources:
- name: source
  type: git
  source:
    uri: https://github.com/nick96/withoutdelay.git
    paths:
    - tasker
- name: go-environment
  type: docker-image
  source:
    repository: golang
    tag: 1.14

jobs:
- name: lint
  plan:
  - get: source
    trigger: true
  - get: go-environment
  - task: lint
    file: source/tasker/ci/task-lint.yml
  - task: test
    file: source/tasker/ci/task-test.yml
