---
resources:
- name: python3.8-environment
  type: docker-image
  source:
    repository: "python:3.8"
- name: temporal-source
  type: git
  source:
    uri: https://github.com/nick96/withoutdelay

jobs:
    - name: lint
      plan:
      - get: python3.8-environment
      - get: temporal-source
      - task: lint
        file: withoutdelay/temporal/ci/task-lint.yml
      - task: test
        file: withoutdelay/temporal/ci/task-test.yml
        
          