---
resources:
- name: temporal-source
  type: git
  source:
    uri: https://github.com/nick96/withoutdelay.git
    paths:
    - temporal

jobs:
    - name: lint
      plan:
      - get: temporal-source
        trigger: true
      - task: lint
        file: temporal-source/temporal/ci/task-lint.yml
      - task: test
        file: temporal-source/temporal/ci/task-lint.yml
        
          